(function(){/*
slideplus image rotator
@author  Levente Hunyadi
@version 1.5.0
@remarks Copyright (C) 2011-2017 Levente Hunyadi
@see     http://hunyadi.info.hu/projects/slideplus
*/
'use strict';var n={rows:2,cols:3,step:"page",loop:!1,random:!1,orientation:"horizontal",layout:"natural",captions:"bottom",links:!0,counter:!0,protection:!1,delay:0,dir:"ltr",lazyload:!0};function v(a){["src","srcset","sizes"].forEach(function(b){if(a.hasAttribute(b)){var c="data-"+b,e=a.getAttribute(b);a.setAttribute(c,e);a.removeAttribute(b)}})}
function w(a){["src","srcset","sizes"].forEach(function(b){var c="data-"+b;if(a.hasAttribute(c)){var e=a.getAttribute(c);a.setAttribute(b,e);a.removeAttribute(c)}})}function x(a){var b=this,c=[].filter.call(a.getElementsByTagName("img"),function(a){return!a.complete&&a.src});this.a=c;if(!(1>c.length)){var e=document.createElement("div");e.classList.add("loadplus-progress");a.appendChild(e);this.b=e;c.forEach(function(a){a.classList.add("loadplus-hidden");v(a);a.preloader=b})}}
x.prototype.load=function(){var a=this;this.a.forEach(function(b){b.src||(b.addEventListener("load",function(){b.classList.remove("loadplus-hidden");var c=a.a.indexOf(b);0<=c&&a.a.splice(c,1);0==a.a.length&&(c=a.b.parentNode)&&c.removeChild(a.b)}),w(b),delete b.preloader)})};x.prototype.load=x.prototype.load;function y(a){a=a||{};for(var b in JSON.parse(JSON.stringify(n)))a[b]=a[b]||n[b];return a}
function z(a){for(var b=a.length;0!==b;){var c=Math.floor(Math.random()*b);--b;var e=a[b];a[b]=a[c];a[c]=e}return a}function A(a){["left","right","top","bottom"].forEach(function(b){a.style.removeProperty(b)})}function B(a){a&&a.forEach(function(a){var b=a.parentNode;b&&b.removeChild(a)})}function C(a){return a.map(function(a){return a.cloneNode(!0)})}
(function(){function a(a,b,c,d){return"@keyframes slideplus-push-"+a+"-"+d+"{0%{transform:translate(0,0);}100%{transform:translate("+100*b/d+"%,"+100*c/d+"%);}}"}for(var b=[],c=1;10>c;++c)[].push.apply(b,[a("left",-1,0,c),a("right",1,0,c),a("top",0,-1,c),a("bottom",0,1,c)]);b=b.join("");c=document.createElement("link");c.rel="stylesheet";c.type="text/css";c.href="data:text/css;charset="+(document.characterSet||"utf-8")+","+encodeURIComponent(b);document.getElementsByTagName("head")[0].appendChild(c)})();
function D(a,b){this.b=a;this.a=b}
function E(a,b,c){function e(a){var b=document.createElement("div");b.classList.add("slideplus-stripe");for(var c=0;c<l;++c){for(var e=document.createElement("div"),u=0;u<m;++u){var d=document.createElement("div");d.classList.add("slideplus-slot");d.classList.add("slideplus-"+h.a.captions);var f=document.createElement("div");f.classList.add("slideplus-aspect");d.appendChild(f);f=document.createElement("div");f.classList.add("slideplus-content");d.appendChild(f);var g=document.createElement("div");
g.classList.add("slideplus-caption");e.appendChild(d);a.push(new D(f,g))}b.appendChild(e)}return b}function g(a){function b(a,b,c,e){var d=document.createElement("a");d.href="#";d.classList.add(b);d.innerHTML="<span>"+c+"</span>";d.addEventListener("click",function(a){a.preventDefault();e()});a.appendChild(d);a.appendChild(document.createTextNode(" "))}function c(a,c){b(d,"slideplus-"+a,"",c)}function e(a,c){b(f,"slideplus-pager",""+c,function(){a!=h.c&&F(h,a)})}var d=document.createElement("div");
d.classList.add("slideplus-navigation");d.dir=q;var f=document.createElement("span");f.classList.add("slideplus-paging");c("first",h.o.bind(h));c("previous",h.i.bind(h));d.appendChild(f);c("next",h.g.bind(h));c("last",h.s.bind(h));d.classList.add("slideplus-"+a);a=h.f.length;for(var u=G(h),g=0,k=1;g<a;g+=u,++k)e(g,k);return d}var h=this;if(a){c=c||function(){return null};var d=a;"noscript"===a.tagName.toLowerCase()&&(d=document.createElement("div"),d.innerHTML=a.innerText);this.a=y(b);this.c=0;d=
[].slice.call(d.getElementsByTagName("li"));this.a.random&&(d=z(d));this.A=d.map(c);this.f=c=d.map(function(a){for(var b=document.createElement("div"),c=a.firstChild;c;c=a.firstChild)b.appendChild(c);return b});var l=this.a.rows,m=this.a.cols;d=this.a.loop;l=Math.max(1,l);m=Math.max(1,m);c.length<=l*m&&(d=!1);this.a.rows=l;this.a.cols=m;this.a.loop=d;var p=this.a.orientation,q=h.a.dir,f=[];if(c.length<2*l*m)for(;f.length<2*l*m;)f=f.concat(C(c));else d&&(f=C(c.slice(0,l*m)),f.length=c.length-l*m,f=
f.concat(c.slice(-l*m)));this.l=f;b.lazyload&&(this.u=c.map(function(a){return new x(a)}));this.w=b=[];b=e(b);b.addEventListener("animationend",function(){H(h)});this.h=b;this.v=d=[];d=e(d);d.classList.add("slideplus-successor");d.classList.add("slideplus-hidden");this.b=d;var k=document.createElement("div");k.classList.add("slideplus-viewport");k.classList.add("slideplus-"+p);k.appendChild(b);k.appendChild(d);var r,t;k.addEventListener("touchstart",function(a){a=a.changedTouches[0];r=a.pageX;t=a.pageY});
k.addEventListener("touchend",function(a){function b(a,b){50<=b-a?h.i.call(h):50<=a-b&&h.g.call(h)}a=a.changedTouches[0];"horizontal"===p?b(r,a.pageX):"vertical"===p&&b(t,a.pageY)});k.addEventListener("mouseenter",function(){var a=h;a.j&&(a.j=!1,I(a))});k.addEventListener("mouseleave",function(){J(h)});b=document.createElement("div");b.classList.add("slideplus-previous");b.classList.add("slideplus-button");b.addEventListener("click",function(a){a.preventDefault();h.i()});k.appendChild(b);b=document.createElement("div");
b.classList.add("slideplus-next");b.classList.add("slideplus-button");b.addEventListener("click",function(a){a.preventDefault();h.g()});k.appendChild(b);this.a.protection&&(document.addEventListener("contextmenu",function(a){k.contains(a.target)&&a.preventDefault()}),document.addEventListener("dragstart",function(a){k.contains(a.target)&&a.preventDefault()}));b=g("top");d=g("bottom");this.m=f=document.createElement("div");f.classList.add("slideplus-container");f.dir=q;(c=c.length>l*m)&&f.appendChild(b);
f.appendChild(k);c&&f.appendChild(d);a.parentNode.replaceChild(f,a);K(this);H(this);0<this.a.delay&&J(h)}}function L(a,b){return 0<=b&&b<a.f.length}function G(a){var b=a.a.rows,c=a.a.cols,e=a.a.orientation;a=a.a.step;var g=0;"horizontal"===e?g="single"===a?b:b*c:"vertical"===e&&(g="single"===a?c:b*c);return g}function M(a,b,c){[].forEach.call(a.m.querySelectorAll(b),function(a){c(a)})}function N(a,b){M(a,b,function(a){a.classList.add("slideplus-hidden")})}
function O(a,b){M(a,b,function(a){a.classList.remove("slideplus-hidden")})}
function K(a){var b=a.f.length,c=b>a.a.rows*a.a.cols,e=G(a);if(!a.a.loop||2>b)c&&0<a.c?(O(a,".slideplus-first"),O(a,".slideplus-previous")):(N(a,".slideplus-first"),N(a,".slideplus-previous")),c&&L(a,a.c+e)?(O(a,".slideplus-next"),O(a,".slideplus-last")):(N(a,".slideplus-next"),N(a,".slideplus-last"));M(a,".slideplus-pager",function(a){a.classList.remove("slideplus-current")});var g=Math.floor(a.c/e);[].forEach.call(a.m.querySelectorAll(".slideplus-paging"),function(a){a.querySelectorAll(".slideplus-pager")[g].classList.add("slideplus-current")})}
function P(a,b){a=a.f.length;return(b%a+a)%a}
function Q(a,b,c){var e=a.a.layout;if("natural"===e){var g=a.a.orientation;"horizontal"===g?e="column":"vertical"===g&&(e="row")}g=a.a.rows;var h=a.a.cols,d=a.a.loop,l=0,m=0;"row"===e?(l=h,m=1):"column"===e&&(l=1,m=g);for(e=0;e<g;++e,c+=l)for(var p=0,q=c;p<h;++p,q+=m){var f=P(a,q),k=a.f[f],r=null;if(k.parentNode){if(d)for(k=f;k<a.l.length&&(r=a.l[k],r.parentNode);k+=a.f.length);}else if(d||L(a,q))r=k;var t=b[e*h+p];k=t.a;k.parentNode&&k.parentNode.removeChild(k);if(r){t=t.b;t.appendChild(r);f=a.A[f];
r=k;var u=document.createElement("textarea");u.innerHTML=f||"";r.innerHTML=u.value;f&&(f=a.a.captions,("top"===f||"bottom"===f?t.firstChild:t.parentNode).appendChild(k))}}}function H(a){a.h.style.removeProperty("animation-name");a.b.style.removeProperty("animation-name");a.b.classList.add("slideplus-hidden");B(a.f);B(a.l);Q(a,a.w,a.c);var b=a.a.rows,c=a.a.cols,e=a.c,g=e-b*c;b=e+2*b*c;a.a.loop||(g=Math.max(0,g),b=Math.min(a.f.length,b));if(a.u)for(;g<b;++g)a.u[P(a,g)].load();R(a)}
function S(a,b,c,e){if(a.b.classList.contains("slideplus-hidden")){I(a);var g=a.a.rows,h=a.a.cols,d=a.a.loop,l=a.a.orientation,m=a.a.step,p="",q="",f=0;"horizontal"===l?(f="single"===m?h:1,p=c,q=e):"vertical"===l&&(f="single"===m?g:1,p=e,q=c);c=a.c+b*G(a);if(d||L(a,c))Q(a,a.v,a.c+b*g*h),A(a.b),b="slideplus-push-"+p+"-"+f,a.h.style.animationName=b,a.b.style.animationName=b,a.b.style[p]="100%",a.b.style[q]="0",a.b.classList.remove("slideplus-hidden"),a.c=P(a,c),K(a)}}
function F(a,b){b!=a.c&&a.b.classList.contains("slideplus-hidden")&&(I(a),Q(a,a.v,b),A(a.b),a.b.style.top="0",a.b.style.left="0",a.h.style.animationName="slideplus-fade-out",a.b.style.animationName="slideplus-fade-in",a.b.classList.remove("slideplus-hidden"),a.c=b,K(a))}E.prototype.o=function(){F(this,0)};E.prototype.i=function(){S(this,-1,"ltr"==this.a.dir?"right":"left","bottom")};E.prototype.g=function(){S(this,1,"ltr"==this.a.dir?"left":"right","top")};
E.prototype.s=function(){var a=G(this),b=this.f.length,c=b%a;F(this,b-(0!=c?c:a))};E.prototype.first=E.prototype.o;E.prototype.previous=E.prototype.i;E.prototype.next=E.prototype.g;E.prototype.last=E.prototype.s;function J(a){a.j||(a.j=!0,R(a))}
function R(a){if(a.j&&!a.timeout){var b=a.a.delay;0<b&&(a.timeout=window.setInterval(function(){for(var b=a.h.getBoundingClientRect(),e=0;2>=e;++e)for(var g=0;2>=g;++g){var h=document.elementFromPoint(b.left+e*b.width/2,b.top+g*b.height/2);a.m.contains(h)&&a.g()}},b))}}function I(a){a.timeout&&(window.clearInterval(a.timeout),a.timeout=null)}E.discover=function(a,b){[].forEach.call(document.querySelectorAll("ul.slideplus, noscript.slideplus"),function(c){new E(c,a,b)})};window.SlidePlusSlider=E;
window.Preloader=x;}).call(this);
