(function(){/*
boxplusx: a versatile lightweight pop-up window engine
@author  Levente Hunyadi
@version 1.0
@remarks Copyright (C) 2009-2017 Levente Hunyadi
@remarks Licensed under GNU/GPLv3, see http://www.gnu.org/licenses/gpl-3.0.html
@see     http://hunyadi.info.hu/projects/boxplusx
*/
'use strict';var ba="function"==typeof Object.defineProperties?Object.defineProperty:function(d,m,k){d!=Array.prototype&&d!=Object.prototype&&(d[m]=k.value)},ca="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function da(d){if(d){for(var m=ca,k=["Object","assign"],l=0;l<k.length-1;l++){var t=k[l];t in m||(m[t]={});m=m[t]}k=k[k.length-1];l=m[k];d=d(l);d!=l&&null!=d&&ba(m,k,{configurable:!0,writable:!0,value:d})}}
var ea="function"==typeof Object.assign?Object.assign:function(d,m){for(var k=1;k<arguments.length;k++){var l=arguments[k];if(l)for(var t in l)Object.prototype.hasOwnProperty.call(l,t)&&(d[t]=l[t])}return d};da(function(d){return d||ea});var fa={id:null,slideshow:0,autostart:!1,loop:!1,preferredWidth:800,preferredHeight:600,useDevicePixelRatio:!0,navigation:"bottom",controls:"below",captions:"below",contextmenu:!0,metadata:!1,dir:"ltr"};
function ha(d,m){function k(){l=!1}var l=!1,t=0,x=0,F=["auto","scroll"];d.addEventListener("mousedown",function(d){var k=window.getComputedStyle(m);if(0<=F.indexOf(k.overflowX)||0<=F.indexOf(k.overflowY))t=d.clientX,x=d.clientY,l=!0,d.preventDefault()});d.addEventListener("mouseup",k);d.addEventListener("mouseout",k);d.addEventListener("mousemove",function(d){l&&(m.scrollLeft-=d.clientX-t,m.scrollTop-=d.clientY-x,t=d.clientX,x=d.clientY)})}
(function(){function d(a){this.S(a)}function m(){}function k(a){var b={};1<a.length&&a.substr(1).split("&").forEach(function(a){var c=a.indexOf("="),g=0<=c?a.substr(c+1):"";b[decodeURIComponent(0<=c?a.substr(0,c):a)]=decodeURIComponent(g)});return b}function l(a){var b=document.createElement("a");b.href=a;a=b.hash.indexOf("!");return{protocol:b.protocol,host:b.host,hostname:b.hostname,port:b.port,pathname:b.pathname,search:b.search,V:k(b.search),hash:b.hash,id:b.hash.substr(1,(0<=a?a:b.hash.length)-
1),U:k(b.hash.substr(Math.max(0,a)))}}function t(a){a=l(a);var b=l(location.href);return a.protocol===b.protocol&&a.host===b.host&&a.pathname===b.pathname&&a.search===b.search}function x(a){return Object.keys(a).map(function(b){return encodeURIComponent(b)+"="+encodeURIComponent(a[b])}).join("&")}function F(a,b){a=a||{};for(var c in JSON.parse(JSON.stringify(b)))Object.prototype.hasOwnProperty.call(a,c)||(a[c]=b[c]);return a}function G(a,b){return a.hasAttribute(b)?a.getAttribute(b):null}function Q(a){var b=
document.createElement("textarea");b.innerHTML=a;return b.value}function q(a,b){b?a.classList.remove("boxplusx-hidden"):a.classList.add("boxplusx-hidden")}function D(a){return!a.classList.contains("boxplusx-hidden")}function r(a,b,c){var f=document.createElement("div");f.classList.add("boxplusx-"+a);b&&f.classList.add("boxplusx-hidden");c&&c.forEach(function(a){f.appendChild(a)});return f}function J(a){return a.map(function(a){return r(a)})}function ia(a,b){if(/\.jpe?g$/i.test(a)){var c=new XMLHttpRequest;
c.open("get",a);c.responseType="blob";c.onload=function(){ja(c.response,b)};c.onerror=function(){b(-1)};c.send()}else b(-2)}function ja(a,b){var c=new FileReader;c.onload=function(){var a=new DataView(c.result);if(65496!=a.getUint16(0))b(-2);else{for(var g=a.byteLength,e=2;e<g;){var h=a.getUint16(e);e+=2;if(65505==h){if(1165519206!=a.getUint32(e+=2)){b(-1);return}h=18761==a.getUint16(e+=6);e+=a.getUint32(e+4,h);var d=a.getUint16(e,h);e+=2;for(var p=0;p<d;p++)if(274==a.getUint16(e+12*p,h))return b(a.getUint16(e+
12*p+8,h))}else if(65280!=(h&65280))break;else e+=a.getUint16(e)}return b(-1)}};c.readAsArrayBuffer(a)}function ka(a){return[].slice.call(a).map(function(a){a:{if(null!==a&&"a"===a.tagName.toLowerCase()){var b=G(a,"data-title");if(null!==b){b=Q(b);break a}if(b=a.querySelector("img"))if(b=G(b,"alt"),null!==b)break a}b=""}a:{if(null!==a&&"a"===a.tagName.toLowerCase()){var f=G(a,"data-summary");if(null!==f){f=Q(f);break a}f=G(a,"title");if(null!==f)break a}f=""}b===f&&(f="");var g="";null!==a&&"a"===
a.tagName.toLowerCase()&&(g=a.href);var e=a.dataset&&a.dataset.download||"",h;a=a.getElementsByTagName("img");0<a.length&&(h=a[0]);return{url:g,image:h,title:b,description:f,download:e}})}function u(a,b){a=this.f.querySelectorAll(".boxplusx-"+a);for(var c=0;c<a.length;++c)b(a[c])}function K(a,b){var c=this;Object.keys(b).forEach(function(f){u.call(c,f,function(g){g.addEventListener(a,b[f].bind(c),!1)})})}function R(a){switch(a){case 0:case 1:return!1}return!0}function v(a){function b(a){switch(a){case 0:return"unavailable";
case 1:return"image";case 2:return"video";case 3:return"embed";case 4:return"document";case 5:return"frame";default:return"none"}}var c=this.s.classList;c.remove("boxplusx-"+b(this.C));c.remove("boxplusx-interactive");this.C=a;c.add("boxplusx-"+b(a));R(a)&&c.add("boxplusx-interactive")}function L(){var a=this,b=y.call(this),c=0==b,f=this.i,g=b>=f.length-1,e=this.a.loop&&!(c&&g),h=0<this.a.slideshow;u.call(this,"previous",function(a){q(a,e||!c)});u.call(this,"next",function(a){q(a,e||!g)});u.call(this,
"start",function(b){q(b,h&&!a.l&&!g)});u.call(this,"stop",function(b){q(b,h&&a.l)});u.call(this,"download",function(a){q(a,!!f[b].download)});u.call(this,"metadata",function(b){var c;if(c=a.a.metadata)c=!!a.f.querySelector(".boxplusx-detail");q(b,c)})}function S(){q(this.D,(this.c>this.v.clientWidth||this.g>this.v.clientHeight)&&!R(this.C));var a=this.D.classList;this.m?a.remove("boxplusx-collapse"):a.add("boxplusx-collapse");a=this.D.classList;this.m?a.add("boxplusx-expand"):a.remove("boxplusx-expand")}
function T(){M.call(this);U.call(this);v.call(this,-1);for(var a=this.b;a.hasChildNodes();)a.removeChild(a.lastChild);q(this.A,!1);q(this.h,!1)}function y(){return this.j[this.j.length-1]}function z(a,b,c){function f(){D(d.h)&&(p.setProperty("max-width",h),M.call(d),q(d.G,!1),y.call(d)>=d.i.length-1&&(d.l=!1),L.call(d),q(d.A,!0),V.call(d),S.call(d),d.l&&W.call(d))}this.w=a;var g=window.getComputedStyle(this.f);b=b||g.getPropertyValue("width");c=c||g.getPropertyValue("height");M.call(this);q(this.A,
!0);var e=this.v.classList;e.remove("boxplusx-fixedaspect");e.remove("boxplusx-draggable");1===a||2===a?(a=this.J.style,a.setProperty("width",this.c+"px"),a.setProperty("padding-top",100*this.g/this.c+"%"),e.add("boxplusx-fixedaspect")):4===a?e.add("boxplusx-draggable"):3===a&&(a=this.s.style,a.setProperty("width",this.c+"px"),a.setProperty("max-height",this.g+"px"));X.call(this);a=g.getPropertyValue("width");e=g.getPropertyValue("height");var h=g.getPropertyValue("max-width"),d=this,p=this.f.style;
b!=a||c!=e?(q(this.A,!1),p.removeProperty("max-width"),p.setProperty("width",b),p.setProperty("height",c),this.f.classList.add("boxplusx-animation"),g=Math.max.apply(null,g.getPropertyValue("transition-duration").split(",").map(function(a){var b=parseFloat(a);return/\ds$/.test(a)?1E3*b:b})),window.setTimeout(f,g)):f();p.setProperty("width",a);p.setProperty("height",e)}function M(){this.f.classList.remove("boxplusx-animation");var a=this.f.style;a.removeProperty("width");a.removeProperty("height")}
function Y(a,b,c){function d(a){c(a);return g.f.offsetHeight}var g=this,e=this.h.clientHeight,h=d(b);if(h<=e)return b;h=d(a);if(h>=e)return c(b),b;for(var k=1;10>k;++k){h=(a+b)/2|0;var p=d(h);p<e?(a=h,h=p):(b=h,h=p)}c(a);return a}function X(){if(2===this.w){var a=this.f.style;Y.call(this,0,1E3,function(b){a.setProperty("max-width",b/10+"%")})}else if(4===this.w||3===this.w){var b=this.s.style;b.removeProperty("max-height");var c=Y.call(this,0,window.innerHeight,function(a){b.setProperty("height",
a+"px")});b.removeProperty("height");b.setProperty("max-height",Math.min(c,this.g)+"px")}}function la(a,b){var c=a.src;if(/^file:/.test(c))b(-3);else{var d=window.EXIF;this.a.metadata&&d?d.getData(a,function(){var c=0,d=Object.assign({},a.iptcdata,a.exifdata);if(0<Object.keys(d).length){var f=d;(d=d.Orientation)&&(c=+d)}b(c,f)}):ia(c,function(a){b(a)})}}function N(a){var b=this,c=this.i[a];this.j.push(a);var d=window.getComputedStyle(this.f),g=d.getPropertyValue("width"),e=d.getPropertyValue("height");
H.call(this);q(this.G,!0);var h=c.title,k=c.description;c=c.url;d=l(c);var p=d.pathname,m=Object.assign({},d.V,d.U);this.c=parseInt(m.width,10)||this.a.preferredWidth;this.g=parseInt(m.height,10)||this.a.preferredHeight;if(t(c))(a=document.getElementById(d.id?d.id:m.target))?(a=a.cloneNode(!0),A.call(this,a,h,k),v.call(this,4),z.call(this,3,g,e)):O.call(this);else if(/\.(gif|jpe?g|png|svg)$/i.test(p)){var C=document.createElement("img");C.addEventListener("load",function(){la.call(b,C,function(a,
c){var d=document.createDocumentFragment(),f=document.createElement("div"),p=document.createElement("div");0<a&&p.classList.add("boxplusx-orientation-"+a);var m=p.style;m.setProperty("background-image",'url("'+C.src+'")');var l=b.a.useDevicePixelRatio?window.devicePixelRatio||1:1,B=C.naturalHeight/l;l=C.naturalWidth/l;5<=a&&8>=a?(b.c=B,b.g=l,m.setProperty("width",100*l/B+"%"),m.setProperty("height",100*B/l+"%")):(b.c=l,b.g=B,m.removeProperty("width"),m.removeProperty("height"));b.m||(a=f.style,a.setProperty("width",
b.c+"px"),a.setProperty("height",b.g+"px"));f.appendChild(p);d.appendChild(f);if(c){f=r("detail",!0);p=document.createElement("table");a=Object.keys(c);m=a.length;a.sort();for(B=0;B<m;++B){l=a[B];var P=document.createElement("tr"),q=document.createElement("td");q.innerText=l;var w=document.createElement("td");w.innerText=c[l];P.appendChild(q);P.appendChild(w);p.appendChild(P)}f.appendChild(p);d.appendChild(f)}A.call(b,d,h,k);b.H.style.setProperty("max-width",b.c+"px");v.call(b,1);z.call(b,b.m?2:4,
g,e)})},!1);C.addEventListener("error",O.bind(this),!1);C.src=c;a<b.i.length-1&&(a=b.i[a+1].url,c=l(a),/\.(gif|jpe?g|png|svg)$/i.test(c.pathname)&&(document.createElement("img").src=a))}else if(/\.(mov|mpe?g|mp4|ogg|webm)$/i.test(p)){var w=document.createElement("video");w.controls=!0;w.addEventListener("loadedmetadata",function(){A.call(b,w,h,k);v.call(b,2);b.c=w.videoWidth;b.g=w.videoHeight;z.call(b,2,g,e)},!1);w.addEventListener("error",O.bind(this),!1);w.src=c}else/\.pdf$/.test(p)?(a=document.createElement("embed"),
a.src=c,a.type="application/pdf",A.call(b,a,h,k),v.call(b,3),z.call(b,2,g,e)):(a=/^https?:\/\/(?:www\.)youtu(?:\.be|be\.com)\/(?:embed\/|watch\?v=|v\/|)([-_0-9A-Z]{11,})/i.exec(c),null!==a?Z.call(this,"https://www.youtube.com/embed/"+a[1]+"?"+x({rel:"0",controls:"1",W:"0"}),h,k):Z.call(this,c,h,k))}function U(){for(var a=this.s;a.hasChildNodes();)a.removeChild(a.lastChild);a=this.f.style;var b=this.J.style,c=this.s.style;b.removeProperty("padding-top");b.removeProperty("width");c.removeProperty("width");
a.removeProperty("max-width");c.removeProperty("max-height")}function A(a,b,c){U.call(this);this.s.appendChild(a);this.H.style.removeProperty("max-width");this.R.innerHTML=b;this.P.innerHTML=c}function O(){v.call(this,0);z.call(this,2)}function Z(a,b,c){var d=this,g=document.createElement("iframe");g.width=""+this.c;g.height=""+this.g;g.src=a;A.call(this,g,b,c);var e=!1;g.addEventListener("load",function(){e||(e=!0,v.call(d,5),z.call(d,1))},!1)}function W(){H.call(this);this.B=window.setTimeout(this.next.bind(this),
this.a.slideshow)}function H(){this.B&&(window.clearTimeout(this.B),this.B=null)}function E(a){switch(this.a.dir){case "rtl":return a.offsetParent.offsetWidth-a.offsetWidth-a.offsetLeft;default:return a.offsetLeft}}function I(a,b){var c=this.b.style;c.setProperty("rtl"==this.a.dir?"right":"left",-a+"px");c.setProperty("transition-duration",5*b+"ms")}function V(){if(D(this.u)){for(var a=0;a<this.b.childNodes.length;++a)this.b.childNodes[a].classList.remove("boxplusx-current");var b=Math.max(this.b.offsetWidth-
this.u.offsetWidth,0),c=this.b.childNodes[y.call(this)];c.classList.add("boxplusx-current");a=-E.call(this,this.b);var d=E.call(this,c);b=Math.min(b,d);a>b&&(a=b);c=Math.max(0,d-this.u.offsetWidth+c.offsetWidth);a<c&&(a=c);I.call(this,a,0)}}function ma(){var a=Math.max(this.b.offsetWidth-this.u.offsetWidth,0);I.call(this,0,a-(a- -E.call(this,this.b)))}function na(){var a=Math.max(this.b.offsetWidth-this.u.offsetWidth,0);I.call(this,a,a- -E.call(this,this.b))}function aa(){I.call(this,-E.call(this,
this.b),0)}window.BoxPlusXDialog=d;m.prototype.L="boxplusx";d.prototype.bind=function(a){function b(a){c.M(d,a)}var c=this;a=[].slice.call(a);var d=ka(a);a.forEach(function(a,c){a.addEventListener("click",function(a){a.preventDefault();b(c)},!1)});return b};d.prototype.S=function(a){function b(){if(n.c>n.v.clientWidth||n.g>n.v.clientHeight)n.m=!n.m,N.call(n,y.call(n))}this.a=F(a,fa);a=r("aspect");var c=r("content"),d=r("expander"),g=r("navbar"),e=r("navigation",!1,[g].concat(J(["rewind","forward"]))),
h=r("viewport",!1,[a,c,d].concat(J(["previous","next"]))),k=r("controls",!1,J("previous next close start stop download metadata".split(" "))),p=r("title"),m=r("description"),l=r("caption",!1,[p,m]),q=r("wrapper",!1,[h,e]);q=r("wrapper",!1,[q,k]);q=r("wrapper",!0,[q,l]);var t=r("progress",!0),u=r("dialog",!1,[q,t]),v=r("container",!0,[u]);this.a.id&&(v.id=this.a.id);l.classList.add("boxplusx-"+this.a.captions);k.classList.add("boxplusx-"+this.a.controls);e.classList.add("boxplusx-"+this.a.navigation);
document.body.appendChild(v);this.h=v;this.f=u;this.A=q;this.v=h;this.H=l;this.R=p;this.P=m;this.J=a;this.s=c;this.D=d;this.u=e;this.b=g;this.G=t;this.i=[];this.j=[];this.B=null;this.l=!1;this.w=2;this.c=this.a.c;this.g=this.a.g;this.C=-1;this.m=!0;var n=this;this.h.addEventListener("click",function(a){a.target===n.h&&n.close.call(n)},!1);K.call(this,"click",{previous:this.F,next:this.next,close:this.close,start:this.start,stop:this.O,metadata:this.T,download:this.download});K.call(this,"mouseover",
{rewind:ma,forward:na});K.call(this,"mouseout",{rewind:aa,forward:aa});this.a.contextmenu||u.addEventListener("contextmenu",function(a){a.preventDefault()});var z=this.a.dir;this.h.dir=z;new ha(h,c);d.addEventListener("click",b);h.addEventListener("dblclick",b);c.addEventListener("mousewheel",function(a){var b="hidden"!=window.getComputedStyle(c).overflowY,d=c.scrollHeight-c.clientHeight;if(b&&0<d){b=c.scrollTop;var e=a.deltaY;(b===d&&0<e||0===b&&0>e)&&a.preventDefault()}});window.addEventListener("keydown",
function(a){var b;if(b=D(n.h)){b=a.target;var c=["input","select","textarea"];b=!(null!==b&&0<=c.indexOf(b.tagName.toLowerCase()))}if(b){b=[27,36,35];switch(z){case "ltr":b.push(37,39);break;case "rtl":b.push(39,37)}b=b.indexOf(a.which||a.keyCode);0<=b&&([n.close,n.I,n.K,n.F,n.next][b].call(n),a.preventDefault())}},!1);var x,A=0;h.addEventListener("touchstart",function(a){x=a.changedTouches[0].pageX});h.addEventListener("touchend",function(a){var b=(new Date).getTime(),c=b-A;0<c&&500>c?a.preventDefault():
n.m&&(a=a.changedTouches[0].pageX,50<=a-x?n.F.call(n):50<=x-a&&n.next.call(n));A=b});window.addEventListener("popstate",function(){if(D(n.h))if(n.j.pop(),0<n.j.length){window.history.pushState({L:"boxplusx"},"");var a=y.call(n);n.j.pop();N.call(n,a)}else T.call(n)},!1);window.addEventListener("resize",function(){D(n.h)&&(X.call(n),V.call(n),S.call(n))})};d.prototype.M=function(a,b){this.i=a;var c=this,d=1<a.length&&"hidden"!=this.a.navigation;q(this.u,d);d&&a.forEach(function(a,b){var d=r("aspect"),
e=r("navimage"),g=r("navitem",!1,[d,e]);g.addEventListener("click",c.o.bind(c,b),!1);var f=a.image;f&&(a=function(){var a=d.style;a.setProperty("width",f.naturalWidth+"px");a.setProperty("padding-top",100*f.naturalHeight/f.naturalWidth+"%");e.style.setProperty("background-image",'url("'+f.src+'")')},f.src&&f.complete?a():(f.addEventListener("load",a),f.preloader&&(a=f.preloader,a.load&&a.load())));e.innerText=b+1+"";c.b.appendChild(g)});this.N(b)};d.prototype.N=function(a){this.j=[];window.history.state&&
"boxplusx"===window.history.state.L?window.history.replaceState(new m,""):window.history.pushState(new m,"");this.a.autostart&&0<this.a.slideshow&&(this.l=!0);q(this.h,!0);q(this.G,!0);this.o(a)};d.prototype.close=function(){H.call(this);T.call(this);this.j=[];window.history.go(-1)};d.prototype.o=function(a){a!=y.call(this)&&N.call(this,a)};d.prototype.I=function(){this.o(0)};d.prototype.F=function(){var a=y.call(this);0<a?this.o(a-1):this.a.loop&&this.K()};d.prototype.next=function(){var a=y.call(this);
a<this.i.length-1?this.o(a+1):this.a.loop&&this.I()};d.prototype.K=function(){this.o(this.i.length-1)};d.prototype.start=function(){0<this.a.slideshow&&(this.l=!0,W.call(this),L.call(this))};d.prototype.O=function(){0<this.a.slideshow&&(this.l=!1,H.call(this),L.call(this))};d.prototype.T=function(){var a=this.f.querySelector(".boxplusx-detail");a&&q(a,!D(a))};d.prototype.download=function(){var a=document.createElement("a");a.href=this.i[y.call(this)].download;document.body.appendChild(a);a.click();
document.body.removeChild(a)};d.discover=function(a,b,c){b=b||"boxplusx";var f=new d(c),g=function(a){var b={};[].forEach.call(a,function(a){var c=a.getAttribute("rel");Object.prototype.hasOwnProperty.call(b,c)||(b[c]=[]);b[c].push(a)});return b}(document.querySelectorAll("a[href][rel^="+b+"]:not([rel="+b+"])"));Object.keys(g).forEach(function(a){f.bind(g[a])});[].filter.call(document.querySelectorAll("a[href][rel="+b+"]"),function(a){f.bind([a])});a||[].filter.call(document.querySelectorAll("a[href]:not([rel^="+
b+"])"),function(a){return/\.(gif|jpe?g|png|svg|mov|mpe?g|ogg|webm)$/i.test(a.pathname)&&!a.target}).forEach(function(a){f.bind([a])})}})();}).call(this);
